### ISSUE TITLE
Fix Image Imports

### ISSUE THREAD

**Issue by ubeytdemirr** [LidiaKovac/M2-Benchmark#1]
Your gog project's image import paths not correct

DO NOT 

```
./M2-Benchmark/gog_assets/logo.png

```

DO

```
./gog_assets/logo.png
```

**Comment by LidiaKovac** [comment]
Thank you, fixed it.

Il giorno sab 24 ott 2020 alle ore 09:03 Ubeyt Demir <
notifications@github.com> ha scritto:

**Comment by ubeytdemirr** [comment]
Great! well done 🎈
